name: Scheduled KB Ingest
on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:
jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ingest pipeline
        run: |
          python -c "from kb_updater.pipeline import run_once; run_once('config.yaml')"
